[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install poetry && poetry install --no-dev --no-interaction"]

[start]
cmd = "poetry run uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
